[package]
name = "oj-gitlab-middleware"
version = "0.1.0"
authors = ["temp"]

[dependencies]
rocket = "0.4.0"
mysql = "~14.2.0"
lazy_static = "~1.2.0"
regex = "~1.0.6"


[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["databases", "mysql_pool"]