[development]
gitlab_token = "test"
databases = {mysql = {url = "mysql://root:chuchuwentiniao@192.168.191.123:3306/ojtest"}}

[staging]
address = "0.0.0.0"
mute_security = false
databases = {redis = {url = "redis://:ef797edb92b6d38a36595102a185edf1e91c69f7@192.168.191.5/1"}}

[production]
address = "0.0.0.0"
